apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-service
spec:
  selector:
    matchLabels:
      app: link-service
  replicas: 1
  template:
    metadata:
      labels:
        app: link-service
    spec:
      containers:
        - name: link-db-service
          image: kadekpradnyana/bonsai-link-table
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_USERNAME
              value: "dekjon"
            - name: MONGO_INITDB_PASSWORD
              value: "Dontlookback"
            - name: MONGO_INITDB_DATABASE
              value: "links"
          ports:
            - containerPort: 27017
        - name: link-service
          image: kadekpradnyana/bonsai-link-mgmt
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGODB_URI
              value: "mongodb://dekjon:Dontlookback@localhost:27017/links"
          ports:
            - containerPort: 3020
            - containerPort: 4020

---
apiVersion: v1
kind: Service
metadata:
  name: link-service
spec:
  type: NodePort
  selector:
    app: link-service
  ports:
    - name: http
      protocol: TCP
      port: 3020
      targetPort: 3020
    - name: rpc
      protocol: TCP
      port: 4020
      targetPort: 4020
