version: "3"

services:
  mongo:
    container_name: bonsai-mongo
    image: kadekpradnyana/bonsai-link-table
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
    ports:
      - 27017:27017
    networks: 
      - bonsai-network
    volumes:
      - bonsai-mongo:/data/db/bonsai

  link-service:
    container_name: bonsai-link-mgmt
    restart: always
    # image: kadekpradnyana/bonsai-user-mgmt
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - /bonsai/user/node_modules
      - .:/bonsai/link
    ports:
      - 3020:3020
      - 4020:4020
    env_file:
      - ./.env
    depends_on:
      - mongo
    networks: 
      - bonsai-network
    environment:
      - NODE_ENV=development

volumes:
  bonsai-mongo:
networks: 
  bonsai-network:
    external: true